### ISSUE TITLE
Remove dag.ReplayingDAGPublisher

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#1173]
The development network is reset. All transactions have the payload attached when needed. This makes the dag.ReplayingDAGPublisher obsolete. The network can directly call the ambassadors to process DID Documents and VCs.

This is required to refactor `dag.Walk`

Steps to take

- [x] #1174
- [ ] #1175
- [ ] #1176

**Comment by gerardsn** [comment]
Steps to take
- [ ] reroute LastTransactionTracker through state + in it from db
- [ ] reroute handlePrivateTX through state
- [ ] Rewrite Network.Subscribe to take over emitEvent from ReplayingDAGPublisher
