### ISSUE TITLE
Create a performance baseline

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#1293]
For each deployment configuration it should be possible to get a baseline performance. The node should not lock when put on load and should respond with correct API return codes. It should also give correct logging output (WARN) when put under load from the network (other nodes).

This is currently blocked by:

- [ ] nodes not in sync when put under load. 2 nodes, one doing 100/s of DID create. The 2 nodes will not get in sync.
- [ ] when applying 200/s DID creates on the VDR API, 100% client timeouts occur and the node gets busy doing stuff.

To fix the 'node is busy doing X':

- [ ] add profile option to executable to get cpu profile from a working node (from docker)
- [ ] run performance test with profile enabled and analyze.

**Comment by woutslakhorst** [comment]
to detect waits:

- send kill signal
- use https://github.com/linuxerwang/goroutine-inspect on logs
