### ISSUE TITLE
Crypto: Create storage abstraction

### ISSUE THREAD

**Issue by stevenvegt** [nuts-foundation/nuts-node#1810]
This is a epic tracking issue.
In order to address NTS-004 #1721 and support multiple crypto storage back-ends #1361, we are going to build a storage abstraction layer which allows developers creating simple storage engines or proxies in their language of choice for their key store of choice.

For this we need multiple things:
* [x] API Specification, published in the docs #1820 
* [x] Build Nuts node client implementation (v5.1) #1819 
* [ ] Vault implementation (beta in v5.1)
* [ ] Remove the current Hashicorp Vault implementation from the nuts-node (v6) #1818 
* [ ] Document the new configuration, including examples for a side care setup
* [ ] Present this during a developers meeting

**Comment by woutslakhorst** [comment]
I doubt if the new Vault implementation fits in the v5.1 timeframe.

**Comment by reinkrul** [comment]
I don't see how this addresses NTS-004 https://github.com/nuts-foundation/nuts-node/issues/1721

Which crypto backend is used by default has nothing to do with where the Vault client lives (in the Nuts Node or in a separate process).

Removing from v5.1 milestone.
