### ISSUE TITLE
Support new authentication means

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#2047]
The means allows for an organization to issue a credential to itself with a very limited lifespan. The contents includes the user as employee. The signing session will create the credential and create a presentation. The presentation is returned as token that can be entered in the `usi` field.

- [x] add specification to RFCs
- [x] alter nuts json-ld context with new `assuranceLevel` field. ['low','substantial','high'] #2048
- [x] alter nuts json-ld context. Include new `NutsEmployeeCredential`. See [playground](https://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%5B%22https%3A%2F%2Fwww.w3.org%2F2018%2Fcredentials%2Fv1%22%2C%22https%3A%2F%2Fw3id.org%2Fsecurity%2Fsuites%2Fjws-2020%2Fv1%22%2C%7B%22%40version%22%3A1.1%2C%22%40protected%22%3Atrue%2C%22id%22%3A%22%40id%22%2C%22type%22%3A%22%40type%22%2C%22nuts%22%3A%22https%3A%2F%2Fnuts.nl%2Fcredentials%2Fv1%23%22%2C%22NutsSelfSignedPresentation%22%3A%22nuts%3ANutsSelfSignedPresentation%22%2C%22NutsEmployeeCredential%22%3A%7B%22%40id%22%3A%22nuts%3ANutsEmployeeCredential%22%2C%22%40context%22%3A%7B%22%40version%22%3A1.1%2C%22%40protected%22%3Atrue%2C%22%40propagate%22%3Atrue%2C%22id%22%3A%22%40id%22%2C%22type%22%3A%22%40type%22%2C%22identifier%22%3A%22schema%3Aidentifier%22%2C%22roleName%22%3A%22schema%3AroleName%22%2C%22member%22%3A%7B%22%40id%22%3A%22schema%3Amember%22%2C%22%40context%22%3A%7B%22type%22%3A%22schema%3APerson%22%2C%22initials%22%3A%22schema%3Ainitials%22%2C%22familyName%22%3A%22schema%3AfamilyName%22%7D%7D%7D%7D%7D%5D%2C%22type%22%3A%5B%22VerifiablePresentation%22%2C%22NutsSelfSignedPresentation%22%5D%2C%22verifiableCredential%22%3A%5B%7B%22type%22%3A%5B%22VerifiableCredential%22%2C%22NutsEmployeeCredential%22%5D%2C%22issuer%22%3A%22did%3Anuts%3A123456789%22%2C%22expirationDate%22%3A%222023-04-03T20%3A34%3A17.687862%2B01%3A00%22%2C%22credentialSubject%22%3A%7B%22id%22%3A%22did%3Anuts%3Aa%22%2C%22identifier%22%3A%22481%22%2C%22roleName%22%3A%22Verpleegkundige%20niveau%202%22%2C%22member%22%3A%7B%22initials%22%3A%22J%22%2C%22familyName%22%3A%22van%20Dijk%22%7D%7D%7D%5D%2C%22proof%22%3A%7B%22challenge%22%3A%22LOGIN%20CONTRACT%22%2C%22type%22%3A%22JsonWebSignature2020%22%2C%22verificationMethod%22%3A%22did%3Anuts%3A123456789%23key-1%22%2C%22created%22%3A%222023-04-03T16%3A34%3A17.687862%2B01%3A00%22%2C%22jws%22%3A%22eyJhbGciOiJFUzI1NiIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..hKcboC8m6YnZPi6ReJAYs0J0Ztn5nxcx2EavoXdtrkWxmE1JZmImW89_8IIgjvfI8XtGeDlEnGywAuY2u7y9Bw%22%7D%7D) #2048
- [x] alter nuts json-ld context. Include `NutsSelfSignedPresentation`. #2048
- [x] #2053
- [x] Add public API where a POST is sent to from the piece of html. (Make this HTML configurable with go templates?)
- [x] Add validation of new Presentation type: Includes signing contract as challenge in proof. Must be signed by same organization as the one that issued the credential. #2075 
- [x] #2168
- [x] #2111
- [x] #2091
- [x] #2170
- [x] Add example to demo-ehr: https://github.com/nuts-foundation/nuts-demo-ehr/pull/372
- [x] Add end-2-end test: https://github.com/nuts-foundation/nuts-go-e2e-test/pull/66

**Comment by woutslakhorst** [comment]
For the new means:

the signing attributes usually come from the means, now they have to be passed by the server. This will require some interface and API changes for the new means.

**Comment by woutslakhorst** [comment]
2 issues encountered when generating testdata using vcr APIs:

can't set VerifiablePresentation type
proofPurpose on VP is always assertionMethod, this should be authentication or omitted?

**Comment by reinkrul** [comment]
Things I noticed in Demo EHR:
- Demo EHR checks presence of the `email` attribute to assert a user has actually authenticated, with the self-signed means it would be `username`. But it should probably `eidas_ial` (which is only set when a user identity is present)
- The Patient FHIR resource doesn't require a user context to read, seems wrong?

**Comment by woutslakhorst** [comment]
There's a PR to cover the first point using `username` as the default.

**Comment by woutslakhorst** [comment]
All done!
