### ISSUE TITLE
Change CRL validator package to PKI engine.

### ISSUE THREAD

**Issue by gerardsn** [nuts-foundation/nuts-node#2085]
Upgrading to an Engine makes it is easier to add a health check and gets rid of duplicate crl validation instances (auth and network maintain their own instance)

- [x]  #2158
- [x] ~Persist CRLs and deny list. This allows for faster startup, and prevent issues when they cannot be downloaded at startup~
- [x] ~Add option to load local deny list (t.b.d. if this can be used at the same time as the `URL` option and if they should just the same key)~
- [x] #2181
- [x] #2209
- [x] Make hard-fail (crl download fails) configurable #2158
- [x] #2084
- [x] #2018
- [x] #2187
- [x] #2278

**Comment by gerardsn** [comment]
Are there any diagnostics that need to be added?

**Comment by woutslakhorst** [comment]
> Are there any diagnostics that need to be added?

Diagnostics provides answers when something is not working correctly (could be fuzzy), then diagnostics could provide an answer. Something broken with CRLs will show up in the health check and in the logs so provide a direct indication to the problem.

An opposite example: high bandwidth usage. There won't be a err log line saying: "high bandwidth usage because another node uses an old version". You have to find that out from diagnostics.

**Comment by reinkrul** [comment]
DNs of certificates in the truststore? Saves back-and-forths explaining how to decode the truststore with OpenSSL

**Comment by gerardsn** [comment]
I like the DNs, but this may clutter the diagnostics since it will show ~10 certs for the production network. For the deny list we could show the number of certs on the deny list as a quick check that it is working? For both parts (deny list + crls) the most interesting thing is probably the last time they were updated, but this will definitely clutter the diagnostics page. IMO all options sound like complexity we do not need right now

**Comment by woutslakhorst** [comment]
> IMO all options sound like complexity we do not need right now

If there's another way to get the info, then other issues should have priority.

**Comment by reinkrul** [comment]
I don't think it's particularly important right now either (but since you asked for input, I did my best to come up with _something_ :-p )

**Comment by gerardsn** [comment]
- Remaining is organize the governance (and hosting + key). 
- How are we going to get the certificate info that we need for a denylist entry. (certificates are not logged)

**Comment by gerardsn** [comment]
See https://www.jsdelivr.com/?docs=gh for a CDN hosting solution for the denylist

**Comment by gerardsn** [comment]
all boxes checked
