### ISSUE TITLE
Use OpenID4VP as authorization method

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#2330]
Tracking issue for all OpenID4VP related things.

Used resources:
- https://www.rfc-editor.org/rfc/rfc6749.html
- https://openid.net/specs/openid-4-verifiable-presentations-1_0.html
- https://api-conformance.ebsi.eu/docs/ct/verifier-functional-flows
- https://api-conformance.ebsi.eu/docs/ct/verifiable-presentation-exchange-guidelines-v3
- https://openid.net/specs/openid-connect-core-1_0.html

Possible task list:
- [ ] find the authorize endpoint of a verifier.
- [ ] retrieve authorization request from verifier authorize endpoint. The authorize endpoint will response with a 302. #2357
- [ ] match requested VCs with wallet and create a VP. #2359 
- [ ] create the authorization response a.k.a. VP token request. #2360 
- [ ] add authorize endpoint to authorization server metadata (authorization_endpoint) (https://www.rfc-editor.org/rfc/rfc8414)
- [ ] Create a scope to presentation_definition mapping.
- [ ] todo

First step would be a wallet to get the authorization request from an authorization endpoint of the issuer. Example (from EBSI):
```
GET from https://my.verifier.com/client_id/authorize
?response_type=code
&scope=openid+ver_test%3Avp_token
&state=tracker%3Dvcfghhj
&client_id=did%3Akey%3Az2dmzD81cgPx8Vki7JbuuMmFYrWPgYoytykUZ3eyqht1j9KbsEYvdrjxMjQ4tpnje9BDBTzuNDP3knn6qLZErzd4bJ5go2CChoPjd5GAH3zpFJP5fuwSk66U5Pq6EhF4nKnHzDnznEP8fX99nZGgwbAh1o7Gj1X52Tdhf7U4KTk66xsA5r
&redirect_uri=openid%3A%2F%2F
&nonce=glkFFoisdfEui43
&client_metadata=%7B%22vp_formats_supported%22%3A%7B%22jwt_vp%22%3A%7B%22alg%22%3A%5B%22ES256%22%5D%7D%2C%22jwt_vc%22%3A%7B%22alg%22%3A%5B%22ES256%22%5D%7D%7D%2C%22response_types_supported%22%3A%5B%22vp_token%22%2C%22id_token%22%5D%2C%22authorization_endpoint%22%3A%22openid%3A%2F%2F%22%7D
```

Discussion points:
- scope, I think the requested scope should be defined by use cases and it must map to a presentation_definition (which VCs to present).
- client_id, since the redirect_uri must be openid:// (don't redirect on result but intercept and process result), there's only one option to use: DIDs. (pre-configured is another option).
- since this would replace authCreds, the patient scope also needs to be added. This can be done in the scope as well by using smart on fhir type of scopes.

A signed response/vp_token request could look like:
```
HTTP 302 Location: openid://
?client_id=did%3Aweb%3Aexample.com
&response_type=vp_token
&scope=openid
&redirect_uri=https%3A%2F%2Fexample.com%2Fdirect_post
&request=eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiIsImtpZCI6IldPeUM2dVpGRjRzS2N2Z1dyaVVFcC1TeTRjT0xRYkctMUdYSjNqU01COEEifQ....izu5hQojnE7d0Bof0oPsPTzMk5-BHRR1D945fkU6szyYpU1cQCAzbiAIoTyIcngJlMGfqYNpDDffZCgg_jN4mA
```

Request has been shortened:
```
JWT Header:
{
  typ: 'JWT',
  alg: 'ES256',
  kid: 'did:web:example.com#WOyC6uZFF4sKcvgWriUEp-Sy4cOLQbG-1GXJ3jSMB8A'
}
JWT Payload:
{
  iss: 'https://example.com,
  aud: 'did:key:z2dmzD81cgPx8Vki7JbuuMmFYrWPgYoytykUZ3eyqht1j9KbsEYvdrjxMjQ4tpnje9BDBTzuNDP3knn6qLZErzd4bJ5go2CChoPjd5GAH3zpFJP5fuwSk66U5Pq6EhF4nKnHzDnznEP8fX99nZGgwbAh1o7Gj1X52Tdhf7U4KTk66xsA5r',
  exp: 1589699162,
  response_type: 'vp_token',
  response_mode: 'direct_post',
  client_id: 'did:web:example.com,
  redirect_uri: 'https://example.com/direct_post',
  scope: 'openid',
  nonce: 'FgkeErf91kfl',
  presentation_definition: {...}
}
```

Note: aud in the JWT and client_id in the authorization request still use did:key in this example. Should be a did:web as well.

The wallet should then create a VP based on the given request. It should find the correct VCs for this. The resulting vp_token is posted to the redirect_uri (form encoded):
```
HTTP POST into: https://my.verifier.com/client_id/direct_post
vp_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiIsImtpZCI6ImRpZDprZXk6ejJkbXpEODFjZ1B4OFZraTdKYnV1TW1GWXJXUGdZb3l0eWtVWjNleXFodDFqOUtic0VZdmRyanhNalE0dHBuamU5QkRCVHp1TkRQM2tubjZxTFpFcnpkNGJKNWdvMkNDaG9QamQ1R0FIM3pwRkpQNWZ1d1NrNjZVNVBxNkVoRjRuS25IekRuem5FUDhmWDk5blpHZ3diQWgxbzdHajFYNTJUZGhmN1U0S1RrNjZ4c0E1ciJ9.....HBfJM7yaYgz0Lm93fGFKnQb56r5DUIRZ_lSWaRFdPspzeI4sD0vTh2r2sSj7f3VjiJLPCc0eZivRuq28YmyUOA
&presentation_submission=%7B%22id%22%3A%22a30e3b91-fb77-4d22-95fa-871689c322e2%22%2C%22definition_id%22%3A%22%3Cdefinition+id%3E%22%2C%22descriptor_map%22%3A%5B%7B%22id%22%3A%22%3Cequals+to+definition+first%3E%22%2C%22path%22%3A%22%24%22%2C%22format%22%3A%22jwt_vp%22%2C%22path_nested%22%3A%7B%22format%22%3A%22jwt_vc%22%2C%22path%22%3A%22%24verifiableCredential%5B0%5D%22%7D%7D%2C%7B%22id%22%3A%22%3Cequals+to+definition+second%3E%22%2C%22path%22%3A%22%24%22%2C%22format%22%3A%22jwt_vp%22%2C%22path_nested%22%3A%7B%22format%22%3A%22jwt_vc%22%2C%22path%22%3A%22%24verifiableCredential%5B1%5D%22%7D%7D%2C%7B%22id%22%3A%22%3Cequals+to+definition+third%3E%22%2C%22path%22%3A%22%24%22%2C%22format%22%3A%22jwt_vp%22%2C%22path_nested%22%3A%7B%22format%22%3A%22jwt_vc%22%2C%22path%22%3A%22%24verifiableCredential%5B2%5D%22%7D%7D%5D%7D
```
With the vp_token as:
```
JWT Header:
{
  typ: 'JWT',
  alg: 'ES256',
  kid: 'did:key:z2dmzD81cgPx8Vki7JbuuMmFYrWPgYoytykUZ3eyqht1j9KbsEYvdrjxMjQ4tpnje9BDBTzuNDP3knn6qLZErzd4bJ5go2CChoPjd5GAH3zpFJP5fuwSk66U5Pq6EhF4nKnHzDnznEP8fX99nZGgwbAh1o7Gj1X52Tdhf7U4KTk66xsA5r'
}
JWT Payload:
{
  iss: 'did:key:z2dmzD81cgPx8Vki7JbuuMmFYrWPgYoytykUZ3eyqht1j9KbsEYvdrjxMjQ4tpnje9BDBTzuNDP3knn6qLZErzd4bJ5go2CChoPjd5GAH3zpFJP5fuwSk66U5Pq6EhF4nKnHzDnznEP8fX99nZGgwbAh1o7Gj1X52Tdhf7U4KTk66xsA5r',
  aud: 'https://my.verifier.com/client_id',
  sub: 'did:key:z2dmzD81cgPx8Vki7JbuuMmFYrWPgYoytykUZ3eyqht1j9KbsEYvdrjxMjQ4tpnje9BDBTzuNDP3knn6qLZErzd4bJ5go2CChoPjd5GAH3zpFJP5fuwSk66U5Pq6EhF4nKnHzDnznEP8fX99nZGgwbAh1o7Gj1X52Tdhf7U4KTk66xsA5r',
  iat: 1589699260,
  nbf: 1589699260,
  exp: 1589699260,
  nonce: 'FgkeErf91kfl',
  jti: 'urn:uuid:0706061a-e2ca-4614-9de7-9c1451935f02',
  vp: {
    '@context': [ 'https://www.w3.org/2018/credentials/v1' ],
    id: 'urn:uuid:0706061a-e2ca-4614-9de7-9c1451935f02',
    type: [ 'VerifiablePresentation' ],
    holder: 'did:key:z2dmzD81cgPx8Vki7JbuuMmFYrWPgYoytykUZ3eyqht1j9KbsEYvdrjxMjQ4tpnje9BDBTzuNDP3knn6qLZErzd4bJ5go2CChoPjd5GAH3zpFJP5fuwSk66U5Pq6EhF4nKnHzDnznEP8fX99nZGgwbAh1o7Gj1X52Tdhf7U4KTk66xsA5r',
    verifiableCredential: [...]
  }
}
```

The nonce is used as challenge in the proof. And the client_id as aud. In the linked data proof format the client_id would have been in the domain field.

=========

This part is a bit of a guess....
Then if I'm not mistaken, the verifier will answer with a 302 containing a code & state (optional). The wallet can then get an access token by using rfc7523 client authentication:

```
POST /token.oauth2 HTTP/1.1
     Host: as.example.com
     Content-Type: application/x-www-form-urlencoded

     grant_type=authorization_code&
     code=n0esc3NRze7LTCu7iYzS6a5acc3f0ogp4&
     client_assertion_type=urn%3Aietf%3Aparams%3Aoauth%3A
     client-assertion-type%3Ajwt-bearer&
     client_assertion=eyJhbGciOiJSUzI1NiIsImtpZCI6IjIyIn0.
     eyJpc3Mi[...omitted for brevity...].
     cC4hiUPo[...omitted for brevity...]
```

For all this to work, sessions need to be stateful and link the vp_token, code and nonces together.

**Comment by woutslakhorst** [comment]
The initial request from the wallet can be matched against an internal DB holding presentation_definitions and authorizations (legal basis, consent, etc). The node could also implement a configurable callback so other DBs can be called to validate the request. Checking of the patient specific scopes needs to be done after the vp_token has been posted to ensure the identity of the wallet is known.

**Comment by woutslakhorst** [comment]
A problem with this scheme is that it doesn't seem to be able to combine multiple wallets. How is the user VP to be combined with the service wallet VP?

**Comment by woutslakhorst** [comment]
An option is to use the openid id_token to relay the user VP. One catch is that in this flow a nonce is supposed to be signed but that would mean a user has to authenticate for each party it's getting data from. We could make an exception by not sending a nonce. Instead we use the DID of the vendor as challenge.

**Comment by reinkrul** [comment]
I'm not 100% sure, but I'm starting to believe you need a Microsoft Azure AD (now Microsoft Entra) environment to issue VCs to the Microsoft wallet: https://learn.microsoft.com/en-us/azure/active-directory/verifiable-credentials/verifiable-credentials-configure-issuer?source=recommendations

We could also issue to Sphereon's (open source) wallet to test compatibility: https://github.com/Sphereon-Opensource/ssi-mobile-wallet

**Comment by woutslakhorst** [comment]
Microsoft wallet also needs an activation through invitation.

**Comment by woutslakhorst** [comment]
Given new insights, this flow is no longer correct.
