### ISSUE TITLE
did:web support

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#2347]
# Why
Although Nuts is specified in RFCs, there are no (known) implementations other than "this" Nuts node.
This is a problem when the ecosystem contains parties that want to interact with Nuts node, but don't actually have a Nuts node. E.g.,
- issuing a care organization credential to a Nuts node's wallet,
- using a Microsoft Authenticator wallet to authenticate a caregiver,
- having the Nuts node issue a credential to a non-Nuts node (?)

# Resources
- did:web specification: https://w3c-ccg.github.io/did-method-web/
- For reference; resolver used in Universal Resolver: https://github.com/decentralized-identity/web-did-resolver

# Stuff to do

- Consuming did:web
   - Implement a resolver
   - Support VCs with web DID (issuer is a did:web, or credential subject is a did:web)
      - Probably good idea to disable it by default, at first
- Producing did:web
- Migrating did:nuts to did:web
   - Aliasing did:nuts with alsoKnownAs?
   - We can only start issuing VCs to did:web when all Nuts nodes have upgraded to a version with did:web support
   - As such, we should try to support consuming did:web as early as possible?
- Write RFC that adds did:web support for Nuts

# issues

 - [x] Expose all nuts did documents via its web url. This requires a publicUrl in the config. All */did.json calls should be intercepted (use middleware). 
 - [x] Write a did:web resolver in its basic form (no tenant id <> public key checking). #2351 
 - [ ] GoldenHammer Part deux: add AlsoKnownAs to DID Documents.

**Comment by woutslakhorst** [comment]
The did:nuts method now also handles service discovery for the DIDs. Without pro-actively pushing DID changes to others, they won't know a DID exists or that it supports a service.

Supporting did:web allows non nuts network parties to use the nuts node as issuer/verifier.

**Comment by reinkrul** [comment]
We should probably make things easier for ourselves and produce did:web in JSON format instead of JSON-LD

**Comment by woutslakhorst** [comment]
> We should probably make things easier for ourselves and produce did:web in JSON format instead of JSON-LD

result wouldn't really be different apart from the `@context` array?

**Comment by reinkrul** [comment]
> > We should probably make things easier for ourselves and produce did:web in JSON format instead of JSON-LD
> 
> result wouldn't really be different apart from the `@context` array?

Yes, and no array compacting (compacting an array with a single value to a scalar/object)

**Comment by reinkrul** [comment]
Do we want only to serve did:web documents as derivative from did:nuts documents? Maybe only at first, until all nodes support did:web. Then did:web should be the preferred DID-method, meaning there should be a store for it (and an implementation of the `DocManipulator` interfaces so they can be updated).

**Comment by reinkrul** [comment]
# Threat Model

These are the threats we identified and want/do not want to protect against.

## Attacker with root access
An attacker has root access to the machine serving the did:web document. This can be a reverse proxy, the Nuts node which the reverse proxy forwards to, or a backing store (e.g., database) from which the did:web document is created.

We do not protect against attackers with root access, since it's almost impossible to do properly and highly dependent on the deployment environment. One way would be to have each did:web document version signed with an offline private key, but that would create a very heavy burden on ops. Note that even Hashicorp Vault does not protect against attackers with root access.

## Attacker spoofing DNS records
An attacker who uses a compromised client network could inject its own DNS responses when a Nuts node resolves a did:web document, trying to get it to resolve the document from its own server. But since did:web is always resolved over HTTPS, the (fake) server will be rejected, since it can't present a valid server certificate for the domain.

**Comment by reinkrul** [comment]
We found out deriving `did:web` from `did:nuts` makes things very complicated: VCs are issued to one or the other, by an issuer identified by one or the other, then VPs are signed again by one of them. Deriving and deciding which one to use in every relevant place is very complex.

As the new features (Discovery Service, OpenID4VP, OpenID4VCI) are all exclusive to `did:web` anyway, we could make things simpler by introducing support to actually create `did:web` documents, instead of deriving them. This would encompass a new VDR API (v2) and storage in SQL.

**API**
- `/did`: create/delete DID (pass type `did:nuts`?). For `did:web` it can use a GUID or any other random string. In future we could allow a named DID instead of a random identifier.
- `/did/{did}`: delete/resolve DID
- `/did/{did}/service` create service
- `/did/{did}/service/{id}` update/delete service
- `/did/{did}/verificationmethod` create key (verification method), by default all relationship types
- `/did/{did}/verificationmethod/{id}` delete key

**Database**
```sql
-- this table is used to store the did:web
create table vdr_didweb
(
    -- did is the fully qualified did:web
    did varchar(255) not null,
    primary key (did)
);

-- this table is used to store the services for a did:web
create table vdr_didweb_service
(
    -- id is the unique id of the service as it appears in the DID document.
    id               varchar(255)  not null,
    -- did references the containing did:web
    did              varchar(255)  not null,
    -- type is the service type
    type             varchar(255)  not null,
    -- service_endpoint is the service endpoint
    service_endpoint varchar(2000) not null,
    primary key (did, id)
);

-- this table is used to store the verification methods for a did:web
create table vdr_didweb_verificationmethod
(
    -- id is the unique id of the verification method as it appears in the DID document.
    id   varchar(255) not null,
    -- did references the containing did:web
    did  varchar(255) not null,
    -- type is the verification method type, e.g. "Ed25519VerificationKey2018" or "JsonWebKey2020"
    methodType varchar(255) not null,
    -- data is a JSON object containing the verification method data, e.g. the public key.
    -- When producing the verificationMethod, data is used as JSON base object and the id and type are added.
    data varchar(2000) not null,
    primary key (did, id)
);
```

**Comment by woutslakhorst** [comment]
LGTM, although I would be careful with the 2000 char limit...

**Comment by reinkrul** [comment]
Basic support has been merged (creating did:web documents), now we need to implement CRUD for services and verification methods. I'd say services has precedence.

**Comment by woutslakhorst** [comment]
@reinkrul ready to close this issue. `aka` could be a separate issue if/when needed.
