### ISSUE TITLE
Implement server-to-server /token endpoint where vp_token is posted

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#2418]
Implements nuts-foundation/nuts-specification#265 (RFC021)

Things to do in order of the flow

- [x] #2484
- [x] #2487
- [x] #2491
- [x] handle presentation definition call and match with config, return definition, #2491
- [x] match definition against wallet #2504
- [x] #2504
- [x] send VP to correct endpoint (from metadata) #2504
- [x] #2495
- [x] store and return access token
- [x] #2541
- [x] errors cases and error returns, check strictmode

**Comment by woutslakhorst** [comment]
note: the /token endpoint should be available in the oauth metadata.
