### ISSUE TITLE
Move non node related documentation to Nuts wiki

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#2854]
Everything on proposed integration, bolts and getting started that are not directly software related will have to move to the Nuts wiki.

## Getting Started

* [x] https://nuts-node.readthedocs.io/en/stable/pages/getting-started/0-hello-world-docker.html uses the Nuts network. Page could go away entirely.
* [x] https://nuts-node.readthedocs.io/en/stable/pages/getting-started/1-running-docker.html remove TLS configuration
* [x] https://nuts-node.readthedocs.io/en/stable/pages/getting-started/2-running-native.html nobody uses this, just use Makefile?
* [x] https://nuts-node.readthedocs.io/en/stable/pages/getting-started/3-configure-your-node.html can go entirely
* [x] https://nuts-node.readthedocs.io/en/stable/pages/getting-started/4-connecting-crm.html rewrite given `did:web` and Discovery Services. See https://github.com/nuts-foundation/nuts-node/issues/2870
* [x] https://nuts-node.readthedocs.io/en/stable/pages/getting-started/5-authentication.html is IRMA and login contract functionality, which must be removed
* [x] https://nuts-node.readthedocs.io/en/stable/pages/getting-started/6-adding-authorizations.html is `NutsAuthorizationCredential`-related, which is replaced by PDPs, documented in the wiki. See https://github.com/nuts-foundation/nuts-node/issues/2871
* [x] https://nuts-node.readthedocs.io/en/latest/pages/getting-started/6-connecting-ehr.html is `did:nuts` Registry and `NutsAuthorizationCredential`-specific, can be removed

## Development:

- [x] https://nuts-node.readthedocs.io/en/stable/pages/development/2-releasing.html references Registry and Demo EHR.

## Deployment&configuration

- [x] https://nuts-node.readthedocs.io/en/stable/pages/deployment/recommended-deployment.html diagram could use some minor changes. Production checklist needs a rewrite to v6 situation
- [x] https://nuts-node.readthedocs.io/en/stable/pages/deployment/resource-requirements.html requires addition for SQL.
- [x] https://nuts-node.readthedocs.io/en/stable/pages/deployment/monitoring.html remove dag visualization and conflicted did documents
- [x] https://nuts-node.readthedocs.io/en/stable/pages/deployment/cli-reference.html only works for did:nuts, did:web is not represented here. Deprecate?
- [x] https://nuts-node.readthedocs.io/en/stable/pages/deployment/backup-restore.html revamp for SQL and Vault
- [x] https://nuts-node.readthedocs.io/en/stable/pages/deployment/key-rotation.html needs rewrite for did:web
- [x] https://nuts-node.readthedocs.io/en/stable/pages/deployment/storage-configuration.html needs rewrite for SQL/Vault
- [x] https://nuts-node.readthedocs.io/en/stable/pages/deployment/tls-configuration.html refers to /n2n and /internal, has some traces of IRMA/Yivi/EmployeeID. If endpoints/ports are revamped, this page needs to change a bit more.
- [x] https://nuts-node.readthedocs.io/en/stable/pages/deployment/production-configuration.html is heavy on http interface binding. Remove legacy authentication. Monitoring Harmful Activity has some references to specific API paths. Mentions XIS/EHR.
- [x] https://nuts-node.readthedocs.io/en/stable/pages/deployment/audit-logging.html could use an update to be more up2date.

## Technology:

- [x] see list below

## Integrating:

- [x] see list below

**Comment by reinkrul** [comment]
I quickly scanned over it, and the Getting Started is really Nuts node-specific since it uses "our" particular REST APIs.

I think most under "Technology" should be on the wiki (except maybe the security model).

**Comment by woutslakhorst** [comment]
> I quickly scanned over it, and the Getting Started is really Nuts node-specific since it uses "our" particular REST APIs.

there are references to care organizations, bolts and other bits

**Comment by gerardsn** [comment]
Technology section is all background information, so can move to the wiki. Only thing to keep is the threat model, but probably restrict scope to nuts-node. In its current form fits wiki too.
Considerations:
- jsonld -> nuts context v1;
- new tech / wip (OpenID4VCI) is sometimes listed here. First under development, and move to relevant section once production ready?

**Comment by gerardsn** [comment]
Integrating:
- https://nuts-node.readthedocs.io/en/latest/pages/integrating/api.html Update to clarify if did:nuts/did:web where relevant. Fix/remove hosting of oapi specs (maybe download as a bundle / postman ...) Currently references schemas in other documents which is not part of the yaml spec, so might not be supported by all code gens?
- https://nuts-node.readthedocs.io/en/latest/pages/integrating/api-authentication.html maybe drop documentation for the legacy token authentication?
- https://nuts-node.readthedocs.io/en/latest/pages/integrating/vc.html Needs to be updated. When all 'magic' has been removed from the API the documentation / examples could be part of the API specs.
- https://nuts-node.readthedocs.io/en/latest/pages/integrating/supported-protocols-formats.html keep & fix bullets
- https://nuts-node.readthedocs.io/en/latest/pages/integrating/faq-errors.html remove: all network related things
- https://nuts-node.readthedocs.io/en/latest/pages/release_notes.html TMI, but fine for now
- https://nuts-node.readthedocs.io/en/latest/pages/roadmap.html remove or replace

**Comment by reinkrul** [comment]
## Getting Started

* https://nuts-node.readthedocs.io/en/stable/pages/getting-started/0-hello-world-docker.html uses the Nuts network. Page could go away entirely.
* https://nuts-node.readthedocs.io/en/stable/pages/getting-started/1-running-docker.html remove TLS configuration
* https://nuts-node.readthedocs.io/en/stable/pages/getting-started/2-running-native.html nobody uses this, just use Makefile?
* https://nuts-node.readthedocs.io/en/stable/pages/getting-started/3-configure-your-node.html can go entirely
* https://nuts-node.readthedocs.io/en/stable/pages/getting-started/4-connecting-crm.html rewrite given `did:web` and Discovery Services.
* https://nuts-node.readthedocs.io/en/stable/pages/getting-started/5-authentication.html is IRMA and login contract functionality, which must be removed
* https://nuts-node.readthedocs.io/en/stable/pages/getting-started/6-adding-authorizations.html is `NutsAuthorizationCredential`-related, which is replaced by PDPs, documented in the wiki
* https://nuts-node.readthedocs.io/en/latest/pages/getting-started/6-connecting-ehr.html is `did:nuts` Registry and `NutsAuthorizationCredential`-specific, can go or be moved to Wiki

**Comment by woutslakhorst** [comment]
All done
