### ISSUE TITLE
sync discovery service spec and implementation

### ISSUE THREAD

**Issue by gerardsn** [nuts-foundation/nuts-node#3298]
Add to implementation from spec:
- [x] retractions must have type RetractedVerifiablePresentation - spec §3.4 #3493
- [x] retraction and retracted VP must have the same expiration time - spec §3.4 https://github.com/nuts-foundation/nuts-specification/pull/279
- [x] ~add support for [PEX relational constraint feature](https://identity.foundation/presentation-exchange/#relational-constraint-feature) `is_holder` and `same_subject`~ will not be implemented
- [x] check proof type with presentation definition #3477 
- [x] reconsider forwarding server request received by clients to the actual server, this is not in the spec. If we keep it, the behavior should be documented and reference security considerations of RFC022
- [x] #3463 
- [x] #3471 
- [x] update `DiscoveryRegistrationCredential` validation according to spec (yes/no include in PD validation)
- [x] #3502

change in spec: -> no longer relevant without usage of `alsoKnownAs` in DIDs
- ~update requirement `all credentials MUST have the same credentialSubject.id`. If this is required, the PD should use PEX relational constraint feature `same_subject`~
- ~update requirement `the key used to sign the presentation MUST be owned by the credential subject (see 4.1): the JWT kid header MUST reference an assertionMethod key from the subject's DID document.`. Part of the requirement sounds like relational constraint feature `is_holder` .~
- ~add clarification on how all credentials in a VP are tied together~

**Comment by woutslakhorst** [comment]
- Add DiscoveryRegistrationCredential

**Comment by woutslakhorst** [comment]
`is_holder` and `same_subject` will not be implemented.

**Comment by woutslakhorst** [comment]
see nuts-foundation/nuts-specification#267

**Comment by woutslakhorst** [comment]
All done
