### ISSUE TITLE
v6 release checklist

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#3472]
- [x] open issues labelled with `final`
- [x] threat modelling/elevation of privilege
- [x] documentation (RTD)
- [x] migration test on development network
- [x] publish RFCs and fix any open issues on the new RFCs (RFC021/RFC022)

**Comment by woutslakhorst** [comment]
Did a test on an instance of the development network. It fixed 2 conflicted documents. Also found an error in de KeyReference table (#3503). Everything else was migrated ok.
