### ISSUE TITLE
Update OAuth flow according to specs

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#358]
This is a tracking issue

- [x] Updated API for token request
- [x] Config for TLS certs (combine network and oauth TLS certs into 1 config)
- [ ] CRL check for certs
- [x] Client API for access token request
- [x] Updated e2e test
- [x] Updated specification (which also mentions JWT grant instead of JWT bearer token)
- [ ] Using AuthorizationCredentials (#94)
- [ ] etc

**Comment by dmeijboom** [comment]
Nut sure why it was closed.. It's not finished so should be open.

**Comment by dmeijboom** [comment]
@woutslakhorst 

> Config for TLS certs (combine network and oauth TLS certs into 1 config)
Isn't this already the case? The auth API is part of the API routes and will use the same TLS config right? Or do you mean the Auth API HTTP Client?

**Comment by woutslakhorst** [comment]
For using the credentials in the oauth flow. A minimum would be to add the IDs of the authorization credentials to the access token request API call. They must also be returned by the introspection call.

**Comment by woutslakhorst** [comment]
TLS part continued in #479
