### ISSUE TITLE
making did:x509-backed credential feature production-ready

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#3582]
TODOs:
- [x] Write RFC nuts-foundation/nuts-specification#283
- [x] Verify that nuts-node is implemented according to the RFC once it is completed
- [x] Check if all documentation is up-to-date, given the latest insights.
  - [x] https://nuts-node.readthedocs.io/en/latest/pages/deployment/certificates.html#did-x509
- [x] nuts-foundation/nuts-node#3583
- [x] nuts-foundation/nuts-node#3587
- [x] nuts-foundation/uzi-did-x509-issuer#11
- [ ] nuts-foundation/uzi-did-x509-issuer#22
- [x] nuts-foundation/uzi-did-x509-issuer#23 (nuts-foundation/uzi-did-x509-issuer#25)
- [x] nuts-foundation/nuts-node#3596
- [x] nuts-foundation/nuts-node#3588
- [x] nuts-foundation/uzi-did-x509-issuer#33
- [x] nuts-foundation/nuts-node#3599
- [x] nuts-foundation/nuts-node#3600
- [x] nuts-foundation/nuts-node#3601
- [x] Make GH Actions build and push Docker image of x509-issuer tool (https://github.com/nuts-foundation/uzi-did-x509-issuer/pull/18)
- [x] https://github.com/nuts-foundation/go-didx509-toolkit/issues/41

Things up for discussion:
- [x] @stevenvegt's remark regarding credential subject structure: https://github.com/Zorgbijjou/zorginzage-homemonitoring/pull/7#issuecomment-2506264492
- [ ] How are parties going to issue their UZI server certificate? This highly depends on the environment, e.g.: tool that connects to a key vault, or uses an on-disk private key. A locally run CLI tool, or a container that you can start, issues the certificate and loads it into the Nuts node, etc.

**Comment by gerardsn** [comment]
- probably could use an e2e test
- (how) do revocations work?

**Comment by woutslakhorst** [comment]
> How are parties going to issue their UZI server certificate? This highly depends on the environment, e.g.: tool that connects to a key vault, or uses an on-disk private key. A locally run CLI tool, or a container that you can start, issues the certificate and loads it into the Nuts node, etc.

clearly document the issuance process and _our_ requirements so people can make a library. Java library is already under construction.

**Comment by woutslakhorst** [comment]
docs on certificates are not totally correct. Should be changed together with PR on #3583

**Comment by reinkrul** [comment]
We'll focus on aligning the implementations on the final design (`subject` map in `credentialSubject` instead of `subject:L` format), so we can release a 6.1 beta version. After that, we'll focus on finishing the RFC.
