### ISSUE TITLE
Scheduled CodeQL action fails for non-master branches

### ISSUE THREAD

**Issue by gerardsn** [nuts-foundation/nuts-node#3629]
see https://github.com/nuts-foundation/nuts-node/actions/runs/12401906128

Same for V5.4 branch:
> [Analyze (V6.0)](https://github.com/nuts-foundation/nuts-node/actions/runs/12401906128/job/34622275716#step:4:60)
Unable to validate code scanning workflow: error: getWorkflow() failed: Error: Expected to find a code scanning workflow file at /home/runner/work/nuts-node/nuts-node/.github/workflows/codeql-analysis-cron-schedule.yml, but no such file existed. This can happen if the currently running workflow checks out a branch that doesn't contain the corresponding workflow file.

Copying the file sounds like an easy fix, but the action should fail if it cannot run successfully.

---

action was added in #3522 with several other concerns

---

Proposed solution:
move to govulncheck and 

TODO:
- [ ] add documentation on release procedure for new major/minor releases (add branch to actions since pattern matching doesn't work) #3656
- [x] add `govulncheck` as a scheduled action #3642, #3645, #3646
- [x] add slack notification to the action if it fails #3652
- [ ] check if CodeQL can still be useful -> leaving it as is for now
