### ISSUE TITLE
Make Nuts Node compliant with the 12factor-app guidelines

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#543]
Being compliant with the 12 factor app guidelines makes it very easy to deploy it to a containerized cloud (e.g. Kubernetes):
https://12factor.net/

This is a summary issue to track whether we're compliant, and the work to be done to become so.

> I. Codebase (One codebase tracked in revision control, many deploys)

OK

> II. Dependencies (Explicitly declare and isolate dependencies)

OK, we use Go Modules.

> III. Config (Store config in the environment)

OK, everything can be configured through the environment (some files, e.g. truststores, are required though).

> IV. Backing services (Treat backing services as attached resources)

Still work to do:

- [x] Externalize IRMA embedded session storage to an external one database: https://github.com/nuts-foundation/nuts-node/issues/542
- [x] Externalize key material to secure storage: https://github.com/nuts-foundation/nuts-node/issues/541

Projections from the DAG (VDR, network and VCR) are just derivatives from the shared network state, so they can be considered local caches. And thus don't need to be externalized.

V. Build, release, run (Strictly separate build and run stages)

OK, we only build on CircleCI.

- [x] Set up a process for releasing and versioning (tagging) the Docker images?

VI. Processes (Execute the app as one or more stateless processes)

We use on-disk BBolt for storage that can be re-retrieved from other sources (sort of a cache), which is OK for now. But if we start storing stuff in BBolt that isn't found anywhere else, we violate this principle.

VII. Port binding (Export services via port binding)

OK, our applications is self-contained and exposes services (e.g. HTTP, gRPC) via bindable ports.

VIII. Concurrency (Scale out via the process model)

OK-ish; when key material and IRMA sessions are externalized you can easily horizontally scale the Nuts node. The network database (cache) could be pretty big though (when the DAG grows), so newly deployed instances won't be functional in seconds.

IX. Disposability (Maximize robustness with fast startup and graceful shutdown)

Our shutdowns are graceful and fast, but there's still work to do:

- [x] Fast startups, since they slower with more TXs on the DAG: https://github.com/nuts-foundation/nuts-node/issues/109

X. Dev/prod parity (Keep development, staging, and production as similar as possible)

OK. The nuts node doesn't really care about what environment it is in. The only trade-off is "strict mode" which allows for potentially unsafe configuration which makes development/testing easier (storage on disk, lenient TLS checking, etc).

XI. Logs (Treat logs as event streams)

OK-ish;

- [x] Logs are written stdout/err so it can be piped to an external log tool. But we still need to improve the analysability: https://github.com/nuts-foundation/nuts-node/issues/538 

XII. Admin processes (Run admin/management tasks as one-off processes)

OK. The Nuts executable that's running the node can also provides a CLI to run admin commands.

And for unsupported cases the REST API can be used directly.

**Comment by reinkrul** [comment]
I'd say as a general practice for the Nuts node; data that isn't replicated from some place else (e.g. private VCs) should be stored in an externalized DBMS? (and that rules out BBolt... :-( )
