### ISSUE TITLE
Private VerifiableCredential messaging

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#549]
Tracking issue for all that is required to support private VerifiableCredentials

- [ ] change Issuer API with addressing field to select who may receive the credential
- [ ] change VCR concept templates with a configuration for private/public so private credentials are not accidently sent as public.
- [ ] add _conclave_, the VCR component that handles async transport and the retry mechanism.
  - [ ] add persistent retry queues
  - [ ] add DLQ queue
  - [ ] add diagnostics
  - [ ] connect to messaging/connection layer
  - [ ] add feedback queue when sending fails/succeeds
- [ ] add API for list of stalled credentials with error reason

**Comment by woutslakhorst** [comment]
This issue expected private VCs to be sent using a private channel. This is no longer true. the Dag is used
