### ISSUE TITLE
VDR: Add fetching specific versions of a DID to the API.

### ISSUE THREAD

**Issue by stevenvegt** [nuts-foundation/nuts-node#572]
DIDs can have multiple versions over time, but these are not exposed at the APIs.

Features:
* [x] Add previous links to resolver meta data #576 
* [ ] ~Fetch a list of versions for a DID~
* [x] Fetch a specific version of a DID #574
* [x] Query for a DID valid at a specified date-time #577

**Comment by stevenvegt** [comment]
A list of versions is probably not needed and requires changes to the DID document store. So, this is now done.
