### ISSUE TITLE
Add generic VerifiableCredential support

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#66]
This is a tracking issue

- [x] implement concept mapping structure #69 
- [x] add NutsOrganizationCredential #100 
- [x] update documentation
- [x] search API #131 
- [x] implement issuing #100
- [x] implement revocation #130 
- [x] implement resolving #125
- [x] connect to network #127 
- [x] keep in line with RFC011 and RFC012
- [x] embed templates using go1.16 #100
- [x] add config params for trusted issuers #149 
- [x] CLI #173
