### ISSUE TITLE
Network: v2 protocol

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#666]
This is a tracking issue

Implement v2 protocol according to RFC017

- [x] protobuf spec #669
- [x] TX Ref XOR binary tree #863
- [x] TX IBLT binary tree #863
- [x] conversation ID, issue + check #819 
- [x] State message #953
- [x] TransactionListQuery message #832 
- [x] TransactionRangeQuery message #950
- [x] TransactionPayloadQuery message
- [x] TransactionSet message #953
- [x] TransactionList message #832 
- [x] TransactionPayload message
- [x] attached payload validation for DID Documents
- [x] Gossip message (Hashes) #816 
- [x] Gossip message (XOR, LC) #951
- [x] Track created TXs for Gossip message

**Comment by woutslakhorst** [comment]
All done
