### ISSUE TITLE
VCR: Add support for VerifiablePresentations

### ISSUE THREAD

**Issue by stevenvegt** [nuts-foundation/nuts-node#684]
**Background**: Currently we don't use the [W3C Verifiable Presentation](https://www.w3.org/TR/vc-data-model/) format. For a holder to present the credential to an issuer, a JWT is used instead. The JWT contains a signature which proves the ownership. This works fine for OAuth based flows.

**Feature**: In order to implement custom flows based on Verifiable Credentials, we also need low level support for Verifiable Presentations:

This requires to refactor the vcr a bit so the three roles: Issuer, holder and verifier are better separated.

Needed for version 1 api
* [x] Create **issuer** role with new apis for issuing and revoking credentials
  * [x] Create vcr api v2 with an issuer and a store for issued credentials  #748 
  * [x] Implement revocation (WIP) #831  
  * [x] #883
* [x] Create **holder** logic for presenting presentations
* [x] Create **verifier** role (WIP)
  * [x] Implement correct LDProofs  (WIP) #810
  * [x] #884
  * [ ] #885

Needed for production scale
* [ ] Index VCs based on JSON-LD canonicalized paths #821 

After this, make sure that:
* [x] #886
  * [x]  Getting started
  * [x] Add v2 api spec to swagger docs
* [ ] Update workshop descriptions (also see https://github.com/nuts-foundation/nuts-workshops/search?q=nuts-demo-ehr): https://github.com/nuts-foundation/nuts-workshops/pull/26
* [x] update registry-admin-demo and demo-ehr 
* [ ] Communicate on Slack

**Comment by woutslakhorst** [comment]
IRMA signatures and UZI signatures are already wrapped in VPs, some logic can be reused/refactored from there.

**Comment by stevenvegt** [comment]
Mostly finished. Remaining points addressed in other issues.
