### ISSUE TITLE
VCR: Switch to JSON-LD for VCs

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#821]
JSON-LD offers some benefits, mostly in flexibility. To support JSON-LD, the go-leia indexing lib must support JSON-LD natively. When it does, queries at the API layer can be passed to the DB and the DB itself can figure out which collection to use by matching the context from the query with the contexts used in a collection.

It would also allow for queries to be syntactically different, but semantically the same.

* [x] #943
* [x] Go-leia should define a new type of store: `LDStore`
* [x] Concepts needs to be refactored to indices (which canonicalized paths to use as index is still needed)
* [x] VCR search APIs must pass the JSON-LD query directly to the DB
* [x] Internal VC searches (auth) could use its own custom context (eg: nuts_organization_search_context) backed by hardcoded structs for easy access to the DB.
* [x] Migrate Existing VCs to new DB
   Existing VCs in the current DB need to be copied to the new DB. Newly issued VCs need to be added to both DBs

**Comment by woutslakhorst** [comment]
All done
